#!/usr/bin/perl

use strict;
use warnings;

use FindBin qw($Bin);
use File::Find;
use MIME::Base64;

my $data = '';
find(
	{
		wanted => sub {
			return unless -f $_;

			my $fn = $_;
			s/^${Bin}\/html//;
			$_ = "/$_" unless /^\//;

			open(my $fh, '<', $fn) || die "Cannot open $fn: $!";
			binmode($fh);
			my $content = join('', <$fh>);
			close($fh);
			$data .= qq{"$_": `} . encode_base64($content) . qq{`,} . "\n";
		},
		no_chdir => 1,
	},
	"$Bin/html"
);

open(my $tpl_fh, '<', "$Bin/swagger_ui.go.tpl") || die "Cannot open $Bin/swagger_ui.go.tpl: $!";
my $template = join('', <$tpl_fh>);
close($tpl_fh);

$template =~ s/\/\* FILES \*\//$data/;

open(my $fh, '>', "$Bin/swagger_ui.go") || die "Cannot open $Bin/swagger_ui.go: $!";
print $fh "// It's autogenerated file, do not modify it!\n";
print $fh $template;
close($fh);
